---
format:
  html:
    css: styles.css
    embed-resources: TRUE
    code-fold: true
    page-layout: full
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = "ragg_png"
)

# load packages
library(shiny)
library(highcharter)
library(dplyr)
library(htmlwidgets)
library(dplyr)
library(htmltools)
library(reactable)
library(reactablefmtr)
library(htmltools)
library(tippy)
library(reactable)
library(tidyr)

# load data
source("prep/00_library.R")
source("prep/01_functions.R")
source("prep/dataframes.R")

state_for_report <- "Georgia"
```


```{r}
# create title for prison sentencing information
prison_sentencing_system_info <- HTML("Prison Sentencing<br>System&#9432;")

# get prison sentencing information for state
prison_sentencing_system_name <- subset(robinainfo, state == state_for_report)$prison_sentencing_system

# reformat text depending on prison sentencing information
prison_sentencing_system <- 
  case_when(
    prison_sentencing_system_name == "Extremely High Indeterminacy" ~ HTML("Extremely High<br>Indeterminacy"),
    prison_sentencing_system_name == "High Indeterminacy"           ~ HTML("High<br>Indeterminacy"),
    prison_sentencing_system_name == "Moderate Indeterminacy"       ~ HTML("Moderate<br>Indeterminacy"),
    prison_sentencing_system_name == "Low Indeterminacy"            ~ HTML("Low<br>Indeterminacy"),
    prison_sentencing_system_name == "Extremely Low Indeterminacy"  ~ HTML("Extremely Low<br>Indeterminacy"))

# get prison sentencing information's definition
prison_sentencing_system_definition <- subset(robinadefinitions, term == prison_sentencing_system_name)$definition 

# assemble all prison sentencing information for the state
prison_sentencing_system_tooltip <- 
  HTML(paste0("To compare the degrees of indeterminacy, or unpredictability
   of time served, of prison-sentencing systems of different jurisdictions,
   we use a qualitative ranking framework based on the Robina Institute's
   Prison-release Discretion And Prison Population Size Report.<br><br><b>", 
   prison_sentencing_system_name, "</b>: ",
   prison_sentencing_system_definition, "."))

# make the information accessible
prison_sentencing_system_info <- paste0('<span aria-label="', prison_sentencing_system_tooltip, '" tabindex="0" role="button">', prison_sentencing_system_info, '</span>')

# get parole eligibility information
parole_eligibility_criteria <- subset(robinaparoleeligibility, state == state_for_report)$general_rules_of_release_eligibility
```


```{r}
# data prep by tab

###################

# Highlights

###################

if (state_for_report %in% unique(parole_eligibility_table_2020$state)) {
  state_data <- parole_eligibility_table_2020 %>% filter(state == state_for_report)
} else {
  state_data <- "No Data"
}

num_people_current   <- sum(state_data$current_count, na.rm = TRUE)
num_people_1_5_years <- sum(state_data$future_1_5_years_count, na.rm = TRUE)




###################

# Parole Eligibility

###################

# save pie chart of most serios sentenced offense by state
if (state_for_report %in% names(all_pie_parole_elgibility_offense)) {
  state_pie_parole_elgibility_offense <- 
    all_pie_parole_elgibility_offense[[state_for_report]] %>% 
    hc_size(width = 200, height = 200)
} else {
  state_pie_parole_elgibility_offense <- "No Data"
}

```

::: narrow-section
```{r}
htmltools::div(
  id = "grid-container",
  style = "display: grid; grid-template-columns: repeat(3, 1fr); justify-items: center;",
  div(id = "highlight-text", formattable::comma(num_people_current, digits = 0)),
  div(id = "highlight-text", formattable::comma(num_people_1_5_years, digits = 0)),
  div(style ="display: block; 
              color: #ff6400; 
              font-size: 1.25em; 
              font-family: Graphik; 
              font-weight: bold; 
              text-align: center;",
      prison_sentencing_system),
  div(id = "bold-text", HTML("Currently Eligible for<br>Parole but in Prison")),
  div(id = "bold-text", HTML("Eligible for Parole in<br>the next 1-5 years")),
  div(id = "bold-text", tippy(prison_sentencing_system_info,
                              placement = "bottom",
                              flip = TRUE,
                              theme = "light",
                              tooltip = prison_sentencing_system_tooltip))
)
```
<br>
:::







::: panel-tabset

## Tab 1

## Tab 2

<center>
```{r}
div(id = "body-section", br(),
    div(id = "big-section-title", "How is Parole Release Eligibility Determined?"), br(),
    div(id = "regular-text", parole_eligibility_criteria), br(), br(),
    div(id = "big-section-title", "People who are Eligible for Parole but Still in Prison"), br(), br(), br()
)
```

```{r}
div(id = "body-section", 
    div(id = "big-section-title", "Most Serious Sentenced Offense for People who are Parole Eligible but Still in Prison"), br(),
    div(id = "pie-chart", state_pie_parole_elgibility_offense), br()
)
```
</center>
<br>

## Tab 3

:::



---
title: "`r state_for_report`"
---



