project:
  type: website

website:
  title: "AV Parole Project"
  description: For CSG Justice Center use only
  favicon: img/favicon.png
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - text: "Project Overview"
        href: index.html
      - text: "National Trends"
        href: national_trends.html
      - text: "State Reports"
        menu:
          - text: "Georgia"
            href: georgia.html
      - text: "Drafts"
        menu:
          - text: "Georgia"
            href: georgia_all.html

format:
  html:
    css: styles.css
    toc: true
    toc-location: left

execute:
  freeze: auto
