project:
  type: website
  resources:
    - img/map_proj_past_parole_eligibility_2023.png

website:
  title: "AV Parole Project"
  description: For CSG Justice Center use only
  favicon: img/favicon.png
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - text: "Home Page"
        href: index.html
      - text: "National Snapshot"
        href: national_trends.html
      - text: "State Reports"
        href: state_report_links.html
      - text: "Key Findings (Research Only)"
        href: key_findings.html

format:
  html:
    css: styles.css
    toc: true
    toc-location: left
    link-external-newwindow: true # added 2025/2/12 to open links in new tab

execute:
  freeze: false # auto (commented out 2025/02/06)
