---
title: "Georgia"
format:
  html:
    css: styles.css
    embed-resources: TRUE
    code-fold: true
    page-layout: full
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
  # dev = "ragg_png"
)

# load packages
library(shiny)
library(highcharter)
library(dplyr)
library(htmlwidgets)
library(dplyr)
library(htmltools)
library(reactable)
library(reactablefmtr)

# load data
source("prep/00_library.R")
source("prep/01_functions.R")
source("prep/dataframes.R")
```

::: highlight-section
```{r}
htmltools::div(
  style = "display: flex; flex-direction: column; align-items: center;",
  div(id = "highlighttext", "The Robina Institute classifies Georgia's prison-sentencing system as highly indeterminate overall.")
)
```
:::

::: narrow-section

<br>

```{r}
# donuts
chart1 <- 
  all_donut_currently_eligible$Georgia %>% 
  hc_chart(width = 250, height = 200) %>%
  hc_title(text = "Currently Eligible<br>for Parole") 

chart2 <- 
  all_donut_future_eligible$Georgia %>% 
  hc_chart(width = 250, height = 200) %>%
  hc_title(text = "Eligible for Parole<br>in the Future") 

chart3 <- 
  all_donut_future_eligible$Georgia %>% 
  hc_chart(width = 250, height = 200) %>%
  hc_title(text = "TBD<br>Finding") 

# combine charts into a single row
# add charts to an HTML div
htmltools::div(
  style = "display:flex; flex-direction: row; align-items: center;",
  chart1,
  chart2,
  chart3
)
```
:::

<br><br>

```{r}
# save charts to call in tabsetPanel in next R chunk

###########
# Overview
###########

# line chart showing the change in prison pop 
# and the change in releases to parole over time
state_line_pop_released_to_parole <- 
  all_line_pop_released_to_parole$Georgia %>% 
  hc_chart(width = 500, height = 400) %>%
  hc_title(text = "Prison Populations and the Number of 
           People Released to Parole by Reporting Year") 

people_released_to_parole_race_state <- 
  people_released_to_parole_race %>% 
  dplyr::filter(state == "Georgia") %>% 
  ungroup() %>% 
  select(race, prop)

people_released_to_parole_sex_state <- 
  people_released_to_parole_sex %>% 
  dplyr::filter(state == "Georgia") %>% 
  ungroup() %>% 
  select(sex, prop)

people_released_to_parole_age_state <- 
  people_released_to_parole_age %>% 
  dplyr::filter(state == "Georgia") %>% 
  ungroup() %>% 
  select(agerlse, prop)

# save race table by state
state_parole_profile_race <- 
    reactable(people_released_to_parole_race_state,
              style = hc_reactable_style,
              theme = hc_reactable_theme,
              defaultColDef = colDef(format = colFormat(separators = TRUE),
                                     align = "left"),
              compact = TRUE,
              fullWidth = FALSE,
              columns = list(
                race = colDef(name = "Race",
                              minWidth = 250),
                prop = colDef(align = "right",
                              name = "",
                              minWidth = 100,
                              format = colFormat(percent = TRUE,
                                                 digits = 1))))
# save sex table by state
state_parole_profile_sex <- 
reactable(people_released_to_parole_sex_state,
          style = hc_reactable_style,
          theme = hc_reactable_theme,
          defaultColDef = colDef(format = colFormat(separators = TRUE),
                                 align = "left"),
          compact = TRUE,
          fullWidth = FALSE,
          columns = list(
            sex  = colDef(name = "Gender",
                          minWidth = 250),
            prop = colDef(align = "right",
                          name = "",
                          minWidth = 100,
                          format = colFormat(percent = TRUE,
                                             digits = 1))))
# save age table by state
state_parole_profile_age <-
reactable(people_released_to_parole_age_state,
          style = hc_reactable_style,
          theme = hc_reactable_theme,
          defaultColDef = colDef(format = colFormat(separators = TRUE),
                                 align = "left"),
          compact = TRUE,
          fullWidth = FALSE,
          columns = list(
            agerlse = colDef(name = "Age",
                             minWidth = 250),
            prop = colDef(align = "right",
                          name = "",
                          minWidth = 100,
                          format = colFormat(percent = TRUE,
                                             digits = 1))))


###########
# Parole Eligibility
###########

# save offense pie by state
state_pie_parole_elgibility_offense <- 
  all_pie_parole_elgibility_offense$Georgia %>% 
  hc_chart(width = 150, height = 75) %>% 
  hc_chart(margin = c(0, 0, 0, 0))

state_current_ped_2020_offenses <- 
  current_ped_2020_offenses %>% 
  dplyr::filter(state == "Georgia") %>% 
  select(-c(state, 
            yearendpop_ped,
            tooltip,
            chart_label))

state_table_parole_elgibility_offense <- 
    reactable(state_current_ped_2020_offenses,
              style = hc_reactable_style,
              theme = hc_reactable_theme,
              defaultColDef = colDef(format = colFormat(separators = TRUE),
                                     align = "left"),
              compact = TRUE,
              fullWidth = FALSE,
              columns = list(
                chart_label   = colDef(show = FALSE),
                offgeneral    = colDef(name = "Most Serious Sentenced Offense",
                                       minWidth = 200),
                n = colDef(name = "Number of People",
                           minWidth = 100,
                           align = "right"),
                prop   = colDef(name = "Percentage of People Eligible for
                                Parole but not yet Released",
                                minWidth = 175,
                                align = "right",
                                format = colFormat(percent = TRUE,
                                                   digits = 1))))
  

###########
# Releases from Prison
###########

state_pie_released_at_ped <- 
  all_pie_released_at_ped$Georgia %>% 
  hc_chart(width = 150, height = 75) %>% 
  hc_chart(margin = c(0, 0, 0, 0))

df1 <- all_pp_by_variable %>%
  filter(state == "Georgia") %>% 
  select(race, pp_by_race) %>%
  distinct()

table_pp_by_race <- 
  reactable(df1,
          style = hc_reactable_style,
          theme = hc_reactable_theme,
          defaultColDef = colDef(format = colFormat(separators = TRUE),
                                 align = "left"),
          compact = TRUE,
          fullWidth = FALSE,
          columns = list(
            race      = colDef(name = "Race/Ethnicity",
                               minWidth = 200),
            pp_by_race = colDef(name = "",
                                minWidth = 175,
                                align = "right",
                                format = colFormat(percent = TRUE,
                                                   digits = 0))))

df1 <- all_pp_by_variable %>%
  filter(state == "Georgia") %>% 
  select(sex, pp_by_sex) %>%
  distinct()

table_pp_by_sex <- 
  reactable(df1,
          style = hc_reactable_style,
          theme = hc_reactable_theme,
          defaultColDef = colDef(format = colFormat(separators = TRUE),
                                 align = "left"),
          compact = TRUE,
          fullWidth = FALSE,
          columns = list(
            sex       = colDef(name = "Gender",
                               minWidth = 200),
            pp_by_sex = colDef(name = "",
                                minWidth = 175,
                                align = "right",
                                format = colFormat(percent = TRUE,
                                                   digits = 0))))

df1 <- all_pp_by_variable %>%
  filter(state == "Georgia") %>% 
  select(offgeneral, pp_by_offgeneral) %>%
  distinct()

table_pp_by_offgeneral <- 
  reactable(df1,
            style = hc_reactable_style,
            theme = hc_reactable_theme,
            defaultColDef = colDef(format = colFormat(separators = TRUE),
                                   align = "left"),
            compact = TRUE,
            fullWidth = FALSE,
            columns = list(
              offgeneral      = colDef(name = "Most Serious Sentenced Offense",
                                       minWidth = 200),
              pp_by_offgeneral = colDef(name = "",
                                        minWidth = 175,
                                        align = "right",
                                        format = colFormat(percent = TRUE,
                                                           digits = 0))))

df1 <- all_pp_by_variable %>%
  filter(state == "Georgia") %>% 
  select(sentlgth, pp_by_sentlgth) %>%
  distinct()

table_pp_by_sentlgth <- 
  reactable(df1,
            style = hc_reactable_style,
            theme = hc_reactable_theme,
            defaultColDef = colDef(format = colFormat(separators = TRUE),
                                   align = "left"),
            compact = TRUE,
            fullWidth = FALSE,
            columns = list(
              sentlgth      = colDef(name = "Maximum Sentence Lenth",
                                     minWidth = 200),
              pp_by_sentlgth = colDef(name = "",
                                      minWidth = 175,
                                      align = "right",
                                      format = colFormat(percent = TRUE,
                                                         digits = 0))))

###########
# Sentencing
###########



###########
# Disparities
###########
```

```{r}
tabsetPanel(
  id = "tabsetpanel",
  
  #####################################
  tabPanel("Overview",
           div(
             style = "display: flex; flex-direction: row; align-items: flex-start;",
             div(
               state_line_pop_released_to_parole,
               div(id = "footnote", 
                   "Source: NCRP Year End Population (2000-2020), Annual Parole Survey (2000-2018)", br(), br()),
               div(
                 id = "regulartext",
                 "More Ideas: ", br(), br(),
                 "Add number of parole return/revocations to the line chart above.", br(),
                 "Add number of people who are parole eligible but not yet released to the line chart above.", br()
               )
             ),
             div(
               style = "flex: 1; margin-left: 5em; display: flex; flex-direction: column; align-items: center;",
               div(class = "sectiontitle", "Profile of People Released to Parole in 2020"),
               div(style = "display: flex; flex-direction: column; align-items: center;",
                   br(),
                   state_parole_profile_race,
                   state_parole_profile_sex,
                   state_parole_profile_age,
                   br()
               ),
               div(id = "footnote", "Source: NCRP Releases (2020). Methodology: 
                   Found people with less than sentence length served and released 
                   unconditionally or conditionally. Removed releases labeled as 
                   Other release (including death, transfer, AWOL, escape).")
             )
           )
  ),
  
  #####################################
  tabPanel("Parole Eligibility",
           div(
             style = "display:flex; flex-direction: row; align-items: flex-start;",
             div(
               style = "flex: 0 0 40%;",
               div(class = "sectiontitle", 
                   "Most Serious Sentenced Offense for People Eligible for 
                   Parole but not yet Released in 2020"),
               state_pie_parole_elgibility_offense,
               div(style = "margin-top: 0em;", state_table_parole_elgibility_offense),
               div(id = "footnote", "Source: NCRP Year End Population (2020)")
             ),
             div(
               style = "flex: 1; margin-left: 10em; display: flex; flex-direction: column; align-items: center;",
               div(class = "sectiontitle", "More Info on Parole Eligibility TBD"),
               div(style = "display: flex; flex-direction: column; align-items: center;",
                   br(),
                   div(id = "regulartext",
                       "Ideas: ", br(), br(),
                       "Is the PED missing? If so, is the data missing because they aren't 
                       parole eligible or because the data wasn't entered?", br()
                   )
               )
             )
           )
  ),
  
  #####################################
  tabPanel("Releases from Prison",
           div(
             style = "display:flex; flex-direction: row; align-items: flex-start;",
             div(
               style = "flex: 0 0 40%;",
               div(class = "sectiontitle", "Timing of Release by Parole Eligibility"),
               state_pie_released_at_ped, br(),
               div(style = "margin-top: 0em; align-items: center;", class = "sectiontitle", 
                   "Predicted Probabilities of Being Released Within 1 Year of Parole Eligibility"),
               br(),
                              div(table_pp_by_race, align = "center"),
               div(table_pp_by_sex, align = "center"),
               div(table_pp_by_offgeneral, align = "center"),
               div(table_pp_by_sentlgth, align = "center"),
               br(),
               div(id = "footnote", 
                   "Source: NCRP Year End Population (2020). Methodology: 
                   Predicted probabilities are calculated using logistic regression
                   --predicts the probabilities of being released within 1 year 
                   based on various predictor variables such as sex, race, admtype, 
                   offgeneral, and sentlgth.")
             ),
             div(
               style = "flex: 1; margin-left: 10em; display: flex; flex-direction: column; align-items: center;",
               div(class = "sectiontitle", "More Info on Releases from Prison TBD"),
               div(style = "display: flex; flex-direction: column; align-items: center;",
                   br(),
                   div(id = "regulartext",
                       "Ideas: ", br(), br(),
                       "Who (demographics and criminal history) is being released 
                       at first eligibility?", br(), br(),
                       
                       "How long after eligibility does release occur?", br(), br(),
                       
                       "How does release vary by the person's demographic and 
                       criminal history  characteristics?", br(), br(),
                       
                       "What is the mean and median time between parole eligibility 
                       and release for all terms, terms with release bfore PED, and 
                       terms with release after PED?", br(), br(),
                       
                       "Number/percentage of release types (conditional vs unconditional) 
                       from X year to Y year.", br(), br(),
                       
                       "What is the mean and median time between parole eligibility 
                       and release for those released after the PED, by maximum 
                       sentence length? (When max sentence length is 1) up to 2 years, 
                       2) 2 to 5 years, 3) 5 to 10 years, 4) 10 to 15 years, and 
                       5) 15 years to less than life)", br(), br(),
                       
                       "From 2000 to 2020, of the people eligible for release in 
                       that year who were released after their PED, what percentage 
                       are released in one year? Will do this by demographics and 
                       criminal history. For example, there will be a trend line 
                       for Black, Hispanic, and White individuals showing the 
                       number of people released within one year from 2000-2020.", br()
                   )
               )
             )
           )
  ),
  
  #####################################
  tabPanel("Sentencing/Length of Stay",
           div(id = "regulartext",
               "Ideas:", br(),br(),
               "The growth or decline of life sentences from X year to Y year 
               (life without parole).", br(), br(),
               "How different is actual time served compared to sentence length 
               pronounced at court?", br(), br(),
               "Length of stay by most serious sentenced offense, maximum sentence 
               length, demographics.", br(), br(),
               "Bar graph showing the proportion of individuals who served at least 10 
               years by demographics and most serious sentenced offense.", br(), br()
           )
  ),
  
  #####################################
  tabPanel("Racial/Ethnic Disparities",
           div(id = "regulartext",
               "Ideas:", br(),br(),
               "This page will show a breakdown of racial/ethnic/gender disparities in 
               parole eligibility, length of stay, maximum sentence length, etc.", br(), br()
           )
  )
)


```



```{r}
# tabsetPanel(
#   id = "tabsetpanel",
# 
#   ############################
#   tabPanel("Overview",
#   ############################
#     htmltools::div(
#       style = "display: flex; flex-direction: row; align-items: flex-start;",
#       htmltools::div(
#         state_line_pop_released_to_parole,
#         div(id = "footnote", 
#             "Source: NCRP Year End Population (2000-2020), Annual Parole Survey (2000-2018)", br(), br()),
#         div(
#           id = "regulartext",
#           "More Ideas: ", br(), br(),
#           "Add number of parole return/revocations to the line chart above.", br(),
#           "Add number of people who are parole eligible but not yet released to the line chart above.", br()
#         )
#       ),
#       htmltools::div(
#         style = "flex: 1; margin-left: 5em; display: flex; flex-direction: column; align-items: center;",
#         tags$div(class = "sectiontitle", "Profile of People Released to Parole in 2020"),
#         htmltools::div(style = "display: flex; flex-direction: column; align-items: center;",
#           br(),
#           state_parole_profile_race,
#           state_parole_profile_sex,
#           state_parole_profile_age,
#           br()
#         ),
#         div(id = "footnote", "Source: NCRP Releases (2020). Methodology: 
#             Found people with less than sentence length served and released 
#             unconditionally or conditionally. Removed releases labeled as 
#             Other release (including death, transfer, AWOL, escape).")
#       )
#     )
#   ),
#   
#   ############################
#   tabPanel("Parole Eligibility",
#   ############################
#   
#     htmltools::div(
#       style = "display:flex; flex-direction: row; align-items: flex-start;",
#       htmltools::div(
#         style = "flex: 0 0 40%;",
#         tags$div(class = "sectiontitle", 
#                  "Most Serious Sentenced Offense for People Eligible for 
#                  Parole but not yet Released in 2020"),
#         state_pie_parole_elgibility_offense,
#         tags$div(style = "margin-top: 0em;", state_table_parole_elgibility_offense),
#         div(id = "footnote", "Source: NCRP Year End Population (2020)")
#       ),
#       
#       htmltools::div(
#         style = "flex: 1; margin-left: 10em; display: flex; flex-direction: column; align-items: center;",
#         tags$div(class = "sectiontitle", "More Info on Parole Eligibility TBD"),
#         htmltools::div(style = "display: flex; flex-direction: column; align-items: center;",
#           br(),
#           div(id = "regulartext",
#             "Ideas: ", br(), br(),
#             "Is the PED missing? If so, is the data missing because they aren't 
#             parole eligible or because the data wasn't entered?", br()
#           )
#         )
#       )
#     )
#   ),
#   
#   ############################
#   tabPanel("Releases from Prison",
#   ############################  
#            
#            htmltools::div(
#              
#              style = "display:flex; flex-direction: row; align-items: flex-start;",
#              
#              htmltools::div(
#                
#                style = "flex: 0 0 40%;",
#                
#                tags$div(class = "sectiontitle", "Timing of Release by Parole Eligibility"),
#                state_pie_released_at_ped, br(),
#                
#                tags$div(style = "margin-top: 0em; align-items: center;", class = "sectiontitle", 
#                         "Predicted Probabilities of Being Released Within 1 Year of Parole Eligibility"),
#                br(),
#                
#                div(table_pp_by_race, align = "center"),
#                div(table_pp_by_sex, align = "center"),
#                div(table_pp_by_offgeneral, align = "center"),
#                div(table_pp_by_sentlgth, align = "center"),
#                br(),
#                
#                div(id = "footnote", 
#                    "Source: NCRP Year End Population (2020). Methodology: 
#                    Predicted probabilities are calculated using logistic regression
#                    --predicts the probabilities of being released within 1 year 
#                    based on various predictor variables such as sex, race, admtype, 
#                    offgeneral, and sentlgth.")
#                
#              ),
#              
#              htmltools::div(
#                style = "flex: 1; margin-left: 10em; display: flex; flex-direction: column; align-items: center;",
#                tags$div(class = "sectiontitle", "More Info on Releases from Prison TBD"),
#                
#                htmltools::div(style = "display: flex; flex-direction: column; align-items: center;",
#                               br(),
#                               
#                               div(id = "regulartext",
#                                   "Ideas: ", br(), br(),
#                                   "Who (demographics and criminal history) is being released at first eligibility?", br(), br(),
#                                   "How long after eligibility does release occur?", br(), br(),
#                                   "How does release vary by the person's demographic and criminal history  characteristics?", br(), br(),
#                                   "What is the mean and median time between parole eligibility and release for all terms, terms with release bfore PED, and terms with release after PED?", br(), br(),
#                                   "Number/percentage of release types (conditional vs unconditional) from X year to Y year.", br(), br(),
#                                   "What is the mean and median time between parole eligibility and release for those released after the PED, by maximum sentence length? (When max sentence length is 1) up to 2 years, 2) 2 to 5 years, 3) 5 to 10 years, 4) 10 to 15 years, and 5) 15 years to less than life)", br(), br(),
#                                   "From 2000 to 2020, of the people eligible for release in that year who were released after their PED, what percentage are released in one year? Will do this by demographics and criminal history. For example, there will be a trend line for Black, Hispanic, and White individuals showing the number of people released within one year from 2000-2020.", br()
#                               ),
#                )
#              )
#            )),
#            
#   ############################
#   tabPanel("Sentencing/Length of Stay",
#   ############################   
#            
#    div(id = "regulartext",
#        "Ideas:", br(),br(),
#        "The growth or decline of life sentences from X year to Y year 
#        (life without parole).", br(), br(),
#        
#        "How different is actual time served compared to sentence length 
#        pronounced at court?", br(), br(),
#        
#        "Length of stay by most serious sentenced offense, maximum sentence 
#        length, demographics.", br(), br(),
#        
#        "Bar graph showing the proportion of individuals who served at least 10 
#        years by demographics and most serious sentenced offense.", br(), br()
#        )
#   ),
#   
#   ############################
#   tabPanel("Racial/Ethnic Disparities",
#   ############################   
#            
#    div(id = "regulartext",
#        "Ideas:", br(),br(),
#        "This page will show a breakdown of racial/ethnic/gender disparities in 
#        parole eligiblity, length of stay, maximum sentence length, etc.", br(), br()
#        )
#   )
#   
# ) # end of tabsetPanel

```














