---
title: "Parole Eligibility by State" 
format:
  html:
    css: styles.css
    embed-resources: TRUE
    code-fold: true
    page-layout: full
    fig_caption: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = "ragg_png"
)

source("prep/00_library.R")
source("prep/01_functions.R")
source("prep/dataframes.R")
```

<br><br>

```{r}
# create a vector of all states
all_states <- state.name

# parole_eligibility_table_2020 created in parole_eligibility_ncrp.R
map_data <- parole_eligibility_table_2020 %>% 
  # add missing states
  complete(state = all_states) %>% 
  
  mutate(current_perc = current_perc*100,
         future_perc  = future_perc*100,
         missing_perc = missing_perc*100,
         
         state_abb = state.abb[match(state, state.name)],
         
         tooltip = 
           paste0("<b>", state, "</b><br><br>",
                  "Percentage of Prison Population<br> Currently Eligible for Release:<br>",
                   paste(round(current_perc, 0), "%</b>", sep = ""), "<br><br>",
                  "Percentage of Prison Population<br> Eligible for Release in the Future:<br>",
                   paste(round(future_perc, 0), "%</b>", sep = ""), "<br><br>",
                 "Percentage of Prison Population<br> with Missing Parole Eligibility Data:<br>",
                   paste(round(missing_perc, 0), "%</b>", sep = ""), "<br><br>",
                 "Total Prison Population:<br>",
                   formattable::comma(yearendpop, digits = 0)),
                  tooltip = str_replace_all(tooltip, "NA%", "No Data")) %>% 
  
  mutate(datalabel = ifelse(is.na(current_perc),
                            paste0("", state_abb, ""),
                            paste0("<p style=", "text-align:center", ">",
                                   state_abb, "", "<br>",
                                   round(current_perc, 0), "%</p>")),
         
         currentperclabel = paste0(round(current_perc, 0), "%"),
         currentperclabel = str_replace_all(currentperclabel, "NA%", "No Data")) 
```

```{r}
# get minimum and maximum value
min_map <- min(map_data$current_perc, na.rm = TRUE)
max_map <- max(map_data$current_perc, na.rm = TRUE)

# create hex map
highchart(height = 575) %>%
  
  hc_chart(
    spacingTop = 1,  # Adjust the top spacing as needed
    spacingRight = 1,
    spacingBottom = 30,
    spacingLeft = 1
  ) %>%
  
  hc_add_series_map(
    map = hex_gj,
    df = map_data,
    joinBy = "state_abb",
    value = "current_perc",
    dataLabels = list(enabled = TRUE, format = "{point.datalabel}",
                      style = list(fontSize = "14px",
                                   fontWeight = "regular",
                                   fontFamily = "Graphik",
                                   textOutline = 0)),
    nullColor = "#e8e8e8",
    accessibility = list(
      enabled = TRUE,
      keyboardNavigation = list(enabled = TRUE),
      point = list(valueDescriptionFormat = "{point.state}, {point.currentperclabel}"))) %>%
  
  hc_colorAxis(min = min_map,
               max = max_map,
               stops = color_stops(4, gradient_colors),
               labels = list(format = "{value}%",
                             style = list(fontSize = "14px"))) %>%
  
  hc_legend(align = "right",
            verticalAlign = "bottom",
            layout = "vertical",
            symbolHeight = 200,
            symbolWidth = 25,
            x = -25,
            y = 0) %>%
  
  hc_xAxis(title = "") %>%
  hc_yAxis(title = "") %>%
  hc_title(
    text = paste0("Percentage of the Prison Population Currently Eligible for Parole"),
    align = "center",
    # x = -30, shifts to the left
    style = list(
      fontWeight = "bold",
      fontFamily = "Graphik",
      fontSize = "2em",
      color = "#3E4B4B",
      useHTML = TRUE)) %>%
  
  hc_tooltip(formatter = JS("function(){return(this.point.tooltip)}")) %>%
  hc_add_theme(hc_theme_map_jc) %>%
  
  hc_plotOptions(series = list(animation = FALSE,
                               cursor = "pointer",
                               borderWidth = 3),
                 accessibility = list(enabled = TRUE,
                                      keyboardNavigation = list(enabled = TRUE),
                                      linkedDescription = paste0("TEXT"),
                                      landmarkVerbosity = "one"),
                 area = list(accessibility = list(description = paste0("TEXT")))
  )
```

<br><br>

<div class="table-container">
```{r}
table_data <- parole_eligibility_table_2020 %>% 
  select(state, 
         yearendpop, 
         current_count, current_perc,
         future_count, future_perc, missing_count, missing_perc)

reactable(table_data,
          style = hc_reactable_style,
          theme = hc_reactable_theme,
          defaultColDef = colDef(format = colFormat(separators = TRUE),
                                 align = "right",
                                 minWidth = 100),
          compact = TRUE,
          fullWidth = FALSE,
          defaultPageSize = 50,
          columnGroups = list(
              colGroup(name = "Currently Eligible for Parole", columns = c("current_perc", "current_count")),
              colGroup(name = "Eligible for Parole in the Future",  columns = c("future_perc", "future_count")),
              colGroup(name = "Missing Parole Eligibility Data", columns = c("missing_perc", "missing_count"))
          ),
          columns = list(
            state         = colDef(name = "State", minWidth = 130, align = "left"),
            current_perc  = colDef(name = "Percentage of Prison Population", 
                                   format = colFormat(percent = TRUE, digits = 1),
                                   style = list(position = "sticky", 
                                                borderRight = "1px solid #d3d3d3"),
                                   headerStyle = list(fontWeight = "normal")),
            future_perc   = colDef(name = "Percentage of Prison Population", 
                                   format = colFormat(percent = TRUE, digits = 1),
                                   style = list(position = "sticky", 
                                                borderRight = "1px solid #d3d3d3"),
                                   headerStyle = list(fontWeight = "normal")),
            missing_perc  = colDef(name = "Percentage of Prison Population", 
                                   format = colFormat(percent = TRUE, digits = 1),
                                   headerStyle = list(fontWeight = "normal")),
            yearendpop    = colDef(name = "Prison Population",
                                   style = list(position = "sticky", borderRight = "1px solid #d3d3d3"),
                                   headerStyle = list(fontWeight = "bold")),
            current_count = colDef(name = "Number of People",
                                   headerStyle = list(fontWeight = "normal")),
            future_count  = colDef(name = "Number of People",
                                   headerStyle = list(fontWeight = "normal")),
            missing_count = colDef(name = "Number of People",
                                   headerStyle = list(fontWeight = "normal"))
          )
)
```
</div>
<br>
<div id="footnote">Source: NCRP Year End Population (2020)</div>
