---
format:
  html:
    css: styles.css
    embed-resources: TRUE
    code-fold: true
    page-layout: full
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = "ragg_png"
)

# load packages
library(shiny)
library(highcharter)
library(dplyr)
library(htmlwidgets)
library(dplyr)
library(htmltools)
library(reactable)
library(reactablefmtr)
library(htmltools)
library(tippy)
library(reactable)
library(tidyr)

# load data
source("prep/00_library.R")
source("prep/01_functions.R")
source("prep/dataframes.R")

state_for_report <- "Idaho"
```


```{r}
# create title for prison sentencing information
prison_sentencing_system_info <- HTML("Prison Sentencing<br>System&#9432;")

# get prison sentencing information for state
prison_sentencing_system_name <- subset(robinainfo, state == state_for_report)$prison_sentencing_system

# reformat text depending on prison sentencing information
prison_sentencing_system <- 
  case_when(
    prison_sentencing_system_name == "Extremely High Indeterminacy" ~ HTML("Extremely High<br>Indeterminacy"),
    prison_sentencing_system_name == "High Indeterminacy"           ~ HTML("High<br>Indeterminacy"),
    prison_sentencing_system_name == "Moderate Indeterminacy"       ~ HTML("Moderate<br>Indeterminacy"),
    prison_sentencing_system_name == "Low Indeterminacy"            ~ HTML("Low<br>Indeterminacy"),
    prison_sentencing_system_name == "Extremely Low Indeterminacy"  ~ HTML("Extremely Low<br>Indeterminacy"))

# get prison sentencing information's definition
prison_sentencing_system_definition <- subset(robinadefinitions, term == prison_sentencing_system_name)$definition 

# assemble all prison sentencing information for the state
prison_sentencing_system_tooltip <- 
  HTML(paste0("To compare the degrees of indeterminacy, or unpredictability
   of time served, of prison-sentencing systems of different jurisdictions,
   we use a qualitative ranking framework based on the Robina Institute's
   Prison-release Discretion And Prison Population Size Report.<br><br><b>", 
   prison_sentencing_system_name, "</b>: ",
   prison_sentencing_system_definition, "."))

# make the information accessible
prison_sentencing_system_info <- paste0('<span aria-label="', prison_sentencing_system_tooltip, '" tabindex="0" role="button">', prison_sentencing_system_info, '</span>')

# get parole eligibility information
parole_eligibility_criteria <- subset(robinaparoleeligibility, state == state_for_report)$general_rules_of_release_eligibility
```


```{r}
# data prep by tab

###################

# Highlights

###################

if (state_for_report %in% unique(parole_eligibility_table_2020$state)) {
  state_data <- parole_eligibility_table_2020 %>% filter(state == state_for_report)
} else {
  state_data <- "No Data"
}

num_people_current   <- sum(state_data$current_count, na.rm = TRUE)
num_people_1_5_years <- sum(state_data$future_1_5_years_count, na.rm = TRUE)


###################

# Overview

###################

# line chart showing the change in prison pop 
# and the change in releases to parole over time
if (state_for_report %in% names(all_line_pop_released_to_parole)) {
  state_line_pop_released_to_parole <- 
    all_line_pop_released_to_parole[[state_for_report]] %>% 
    hc_size(width = 550, height = 400) %>%
    hc_title(text = "Trends in Prison Population, Releases to Parole, and Parole Eligibility")
} else {
  state_line_pop_released_to_parole <- "No Data"
}



###################

# Parole Eligibility

###################

# save bar chart of people eligible for parole but still in prison by state
if (state_for_report %in% names(all_bar_parole_elgibility_race)) {
  state_bar_parole_elgibility_race <- 
    all_bar_parole_elgibility_race[[state_for_report]] %>% 
    hc_size(width = 500, height = 350) %>% 
    hc_title(text = "People who are Parole Eligible but Still in Prison by Race in 2020")
} else {
  state_bar_parole_elgibility_race <- "No Data"
}

# save pie chart of most serious sentenced offense by state
if (state_for_report %in% names(all_pie_parole_elgibility_offense)) {
  state_pie_parole_elgibility_offense <- 
    all_pie_parole_elgibility_offense[[state_for_report]] %>% 
    hc_size(width = 600, height = 300) %>% 
    hc_title(text = "Most Serious Sentenced Offense for People who are Parole Eligible but Still in Prison in 2020")
} else {
  state_pie_parole_elgibility_offense <- "No Data"
}

# save sentence about serious offense by state
if (state_for_report %in% names(all_sentence_parole_elgibility_offense)) {
  state_sentence_parole_elgibility_offense <- 
    all_sentence_parole_elgibility_offense[[state_for_report]]
} else {
  state_sentence_parole_elgibility_offense <- ""
}


###################

# Releases from Prison

###################

# save adm type by release timing by state
if (state_for_report %in% names(all_bar_released_at_ped_admtype_2020)) {
  state_bar_released_at_ped_admtype_2020 <- 
    all_bar_released_at_ped_admtype_2020[[state_for_report]] %>%
    hc_size(height = 300, width = 475) %>%
    hc_title(text = "Timing of Release by Parole Eligibility and Admission Type in 2020")
} else {
  state_bar_released_at_ped_admtype_2020 <- "No Data"
}



###################

# Disparities

###################

# graph showing the time from PED to release by race and ethnicity
if (state_for_report %in% names(all_time_between_release_ped_2020_by_race)) {
  state_time_between_release_ped_by_race <- 
    all_time_between_release_ped_2020_by_race[[state_for_report]] %>% 
    hc_title(text = "Time from PED to Release by Race and Ethnicity in 2020") %>% 
    hc_size(height = 300, width = 475)
} else {
  state_time_between_release_ped_by_race <- "No Data"
}


#####
# Predicted Probabilities
#####

df1 <- all_pp_by_variable %>%
  filter(state == state_for_report) %>% 
  select(race, pp_by_race) %>%
  distinct()

table_pp_by_race <- 
  reactable(df1,
          style = hc_reactable_style,
          theme = hc_reactable_theme,
          defaultColDef = colDef(format = colFormat(separators = TRUE),
                                 align = "left"),
          compact = TRUE,
          fullWidth = FALSE,
          columns = list(
            race      = colDef(name = "Race/Ethnicity",
                               minWidth = 200),
            pp_by_race = colDef(name = "",
                                minWidth = 175,
                                align = "right",
                                format = colFormat(percent = TRUE,
                                                   digits = 0))))

df1 <- all_pp_by_variable %>%
  filter(state == state_for_report) %>% 
  select(sex, pp_by_sex) %>%
  distinct()

table_pp_by_sex <- 
  reactable(df1,
          style = hc_reactable_style,
          theme = hc_reactable_theme,
          defaultColDef = colDef(format = colFormat(separators = TRUE),
                                 align = "left"),
          compact = TRUE,
          fullWidth = FALSE,
          columns = list(
            sex       = colDef(name = "Gender",
                               minWidth = 200),
            pp_by_sex = colDef(name = "",
                                minWidth = 175,
                                align = "right",
                                format = colFormat(percent = TRUE,
                                                   digits = 0))))

df1 <- all_pp_by_variable %>%
  filter(state == state_for_report) %>% 
  select(offgeneral, pp_by_offgeneral) %>%
  distinct()

table_pp_by_offgeneral <- 
  reactable(df1,
            style = hc_reactable_style,
            theme = hc_reactable_theme,
            defaultColDef = colDef(format = colFormat(separators = TRUE),
                                   align = "left"),
            compact = TRUE,
            fullWidth = FALSE,
            columns = list(
              offgeneral      = colDef(name = "Most Serious Sentenced Offense",
                                       minWidth = 200),
              pp_by_offgeneral = colDef(name = "",
                                        minWidth = 175,
                                        align = "right",
                                        format = colFormat(percent = TRUE,
                                                           digits = 0))))

df1 <- all_pp_by_variable %>%
  filter(state == state_for_report) %>% 
  select(sentlgth, pp_by_sentlgth) %>%
  distinct()

table_pp_by_sentlgth <- 
  reactable(df1,
            style = hc_reactable_style,
            theme = hc_reactable_theme,
            defaultColDef = colDef(format = colFormat(separators = TRUE),
                                   align = "left"),
            compact = TRUE,
            fullWidth = FALSE,
            columns = list(
              sentlgth      = colDef(name = "Maximum Sentence Lenth",
                                     minWidth = 200),
              pp_by_sentlgth = colDef(name = "",
                                      minWidth = 175,
                                      align = "right",
                                      format = colFormat(percent = TRUE,
                                                         digits = 0))))

```

::: narrow-section
```{r}
htmltools::div(
  id = "grid-container",
  style = "display: grid; grid-template-columns: repeat(3, 1fr); justify-items: center;",
  div(id = "highlight-text", formattable::comma(num_people_current, digits = 0)),
  div(id = "highlight-text", formattable::comma(num_people_1_5_years, digits = 0)),
  div(style ="display: block; 
              color: #ff6400; 
              font-size: 1.25em; 
              font-family: Graphik; 
              font-weight: bold; 
              text-align: center;",
      prison_sentencing_system),
  div(id = "bold-text", HTML("Currently Eligible for<br>Parole but in Prison")),
  div(id = "bold-text", HTML("Eligible for Parole in<br>the next 1-5 years")),
  div(id = "bold-text", tippy(prison_sentencing_system_info,
                              placement = "bottom",
                              flip = TRUE,
                              theme = "light",
                              tooltip = prison_sentencing_system_tooltip))
)
```
:::

<br>



::: panel-tabset 

## Parole Eligibility

<center>
```{r}
div(id = "body-section", br(),
    div(id = "big-section-title", "How is Parole Release Eligibility Determined?"), br(),
    div(id = "regular-text", parole_eligibility_criteria), br(), br(),
    div(id = "big-section-title", "People who are Eligible for Parole"), br(), 
    div(id = "bar-chart", state_bar_parole_elgibility_race), br()
)
```

```{r}
div(id = "body-section", 
    div(id = "big-section-title", "Offenses"), br(),
    div(id = "regular-text", state_sentence_parole_elgibility_offense), br(), 
    div(id = "pie-chart", state_pie_parole_elgibility_offense), br()
)
```

</center>
<br>






## Prison Population

<center>
```{r}
div(id = "body-section", 
    div(id = "line-chart", state_line_pop_released_to_parole)
    )
```
</center>
<br>






## Length of Stay

<center>
```{r}


```
</center>
<br>






## Releases from Prison

<center>
```{r}
div(id = "body-section", state_bar_released_at_ped_admtype_2020)
```
</center>
<br>






## Disparities

<center>
```{r}
div(id = "body-section", 
    div(id = "bar-graph", state_time_between_release_ped_by_race), br(), 
    div(id = "section-title", "Predicted Probabilities of Being Released Within 1 Year of Parole Eligibility in 2020"), br(),
         div(id = "reactable-table",
             table_pp_by_race,
             table_pp_by_sex,
             table_pp_by_offgeneral,
             table_pp_by_sentlgth)
    )
```
</center>
<br>

:::

---
title: "`r state_for_report`"
---











