#######################################
# Project: AV Parole
# File: historical_ncrp_term_records.R
# Authors: Mari Roberts
# Date last updated: August 1, 2024 (MAR)
#
# Description:
#    This script processes the NCRP term records data for the years 2014 to 2020.
#    The data is loaded from raw `.rda` files, cleaned, and then saved as separate
#    Excel files for each year. The cleaning process involves renaming columns,
#    trimming strings, and organizing the data for analysis.
#
# Purpose:
#    The cleaned data files generated by this script serve as base datasets for
#    imputation work performed by Sebastián Guzmán in Stata. This preprocessing
#    ensures that the data is uniform and ready for statistical analysis.
#
# Overview of Steps:
#  1. **Define Variables**: Sets up the years, ICPSR codes, and version numbers needed
#     to load the data files for each reporting year.
#  2. **Data Loading Loop**: Iterates over each year and ICPSR code, loading the data
#     from the specified path, cleaning it, and preparing it for export.
#  3. **Data Cleaning**: Mutates specific columns to remove unwanted characters and
#     trims whitespace from all values. Cleans up column names and ensures the data is
#     well-structured.
#  4. **Save Cleaned Data**: Constructs file names and saves the cleaned data as Excel
#     files (currently commented out for manual activation).
#  5. **2018 Data Update**: Handles the special case for 2018, as this data was recently
#     updated and needs to be processed separately. The updated data is cleaned and
#     prepared for saving as a CSV file.
#######################################

# Define the years, ICPSR codes, and versions to be used in the loop
# This sets up the variables needed to iterate through the NCRP datasets from 2014 to 2020
years <- 2014:2020
icpsr_codes <- c("36404", "36862", "37021", "37951", "37973", "38048", "38492")
versions <- c("V2", "V1", "V1", "V1", "V1", "V1", "V1")

# Last Run: 10/1/2024
# Loop through each year and corresponding ICPSR code to load, clean, and prepare the data
# The cleaned data will be saved to an analysis directory on SharePoint
# Note: Seba manually renamed files to version "v1"
for (i in seq_along(years)) {
  # Load the data file for the current ICPSR code and version
  load(paste0(sp_data_path, "/data/raw/NCRP/ICPSR_", icpsr_codes[i], "-",
              versions[i], "/ICPSR_", icpsr_codes[i], "/DS0001/", icpsr_codes[i], "-0001-Data.rda"))

  # Identify the name of the loaded data object and assign it to ncrp_term_records
  data_name <- ls(pattern = paste0("da", icpsr_codes[i]))
  ncrp_term_records <- get(data_name) |>
    # Add a new column for the report year
    mutate(rptyear = years[i]) |>
    # Clean the column names
    clean_names() |>
    # Trim the first 5 or 6 characters from certain string variables
    mutate(across(c(state), ~ str_sub(., 6, -1))) |>
    mutate(across(c(sex, admtype, offgeneral,
                    education, sentlgth, offdetail, race,
                    ageadmit, agerelease, timesrvd, reltype), ~ str_sub(., 5, -1))) |>
    # Trim whitespace from all columns
    mutate(across(everything(), trimws)) |>
    # Reorder the columns to have rptyear and state first
    select(rptyear, state, everything())

  # Construct the file name with the current date and save the file path
  file_name <- paste0("ncrp_term_records_", years[i], "_", format(Sys.Date(), "%Y%m%d"), ".xlsx")
  full_file_path <- file.path(paste0(sp_data_path, "/data/analysis/clean_files"), file_name)

  # Save the cleaned data to an Excel file (currently commented out for manual activation)
  # write.xlsx(ncrp_term_records, full_file_path)

  # Remove the loaded data from memory to free up space
  rm(list = data_name)
}

# Load and process the updated 2018 NCRP data separately
# This section specifically handles the updated 2018 data file
# Last Run: 10/17/2024
load(file.path(sp_data_path, "/data/raw/NCRP/ICPSR_37973-V2/ICPSR_37973/DS0001/37973-0001-Data.rda"))

# Clean and transform the 2018 data, similar to the loop above
ncrp_term_records_2018 <- da37973.0001 |>
  # Add a column for the report year
  mutate(rptyear = 2018) |>
  # Clean the column names
  clean_names() |>
  # Trim the first 5 or 6 characters from string variables
  mutate(across(c(state), ~ str_sub(., 6, -1))) |>
  mutate(across(c(sex, admtype, offgeneral,
                  education, sentlgth, offdetail, race,
                  ageadmit, agerelease, timesrvd, reltype), ~ str_sub(., 5, -1))) |>
  # Trim whitespace from all columns
  mutate(across(everything(), trimws)) |>
  # Reorder the columns to have rptyear and state first
  select(rptyear, state, everything())

# Construct the file name for the 2018 data and save the file path
file_name <- paste0("ncrp_terms_", "2018", "_", "v1.csv")
full_file_path <- file.path(paste0(sp_data_path, "/data/analysis/clean_files"), file_name)

# Save the cleaned 2018 data to a CSV file (currently commented out for manual activation)
# write.csv(ncrp_term_records_2018, full_file_path)
