---
title: "Georgia"
format:
  html:
    css: styles.css
    embed-resources: TRUE
    code-fold: true
    page-layout: full
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = "ragg_png"
)

# load packages
library(shiny)
library(highcharter)
library(dplyr)
library(htmlwidgets)
library(dplyr)
library(htmltools)
library(reactable)
library(reactablefmtr)
library(htmltools)
library(tippy)

# load data
source("prep/00_library.R")
source("prep/01_functions.R")
source("prep/dataframes.R")

state_for_report <- "Georgia"



pe_length <- c("1/3", "6", "9", "7", "7 or 1/3")
pe_unit   <- c("Term", "Months", "Months", "Years", "Years or Term")
pe_sentence <- c("Generally when parole consideration occurs",
                 "Must be served for misdemeanor sentences",
                 "Must be served for felony sentences",
                 "Must be served for a sentence of 21 years or more (excluding life sentences)",
                 "Must be served for convictions of serious crimes such as aggravated assault, incest, or drug trafficking")
pe_criteria <- data.frame(pe_length, pe_unit, pe_sentence)

library(reactable)
library(tidyr)

pe1 <- c("1/3 Term", "Generally when parole consideration occurs")
pe2 <- c("6 Months", "Must be served for misdemeanor sentences")
pe3 <- c("9 Months", "Must be served for felony sentences")
pe4 <- c("7 Years", "Must be served for a sentence of 21 years or more (excluding life sentences)")
pe5 <- c("7 Years or 1/3 Term", "Must be served for convictions of serious crimes such as aggravated assault, incest, or drug trafficking")

# Reshape the data into a long format
df1 <- data.frame(pe1, pe2, pe3)
df2 <- data.frame(pe4, pe5)

pe_criteria_table1 <- reactable(
  data = df1,
  style = hc_reactable_style,
  theme = reactableTheme(borderColor = "#fff",
                 stripedColor = "#fff",
                 cellStyle = list(display = "flex",
                                  flexDirection = "column",
                                  justifyContent = "center")),
  columns = list(
    pe1 = colDef(align = "center", name = "", minWidth = 80),
    pe2 = colDef(align = "center", name = "", minWidth = 80),
    pe3 = colDef(align = "center", name = "", minWidth = 80)
  ),
  rowStyle = function(index) {
    if (index %in% c(1)) {
      list(fontWeight = "bold",
           fontSize = "20px",
           marginBottom = "-10px")
    } else if (index %in% c(2)) {
      list(fontSize = "14px")
    }
  }
)

pe_criteria_table2 <- reactable(
  data = df2,
  style = hc_reactable_style,
  theme = reactableTheme(borderColor = "#fff",
                 stripedColor = "#fff",
                 cellStyle = list(display = "flex",
                                  flexDirection = "column",
                                  justifyContent = "center")),
  columns = list(
    pe4 = colDef(align = "center", name = "", minWidth = 80),
    pe5 = colDef(align = "center", name = "", minWidth = 80)
  ),
  rowStyle = function(index) {
    if (index %in% c(1)) {
      list(fontWeight = "bold",
           fontSize = "20px",
           marginBottom = "-10px")
    } else if (index %in% c(2)) {
      list(fontSize = "14px")
    }
  }
)

```


```{r}
prison_sentencing_system <- HTML("Highly<br>Indeterminate")

prison_sentencing_system_info <- HTML("Prison Sentencing<br>System&#9432;")

prison_sentencing_system_tooltip <- 
  HTML("To compare the degrees of indeterminacy, or unpredictability
   of time served, of prison-sentencing systems of different jurisdictions,
   we use a qualitative ranking framework based on the Robina Institute's
   Prison-release Discretion And Prison Population Size Report.<br><br>
   <b>High indeterminacy:</b> More than 60-80 percent indeterminacy (first prospect of
   release at 20-39.99 percent of judicial maximum)")

# make the tippy accessible
prison_sentencing_system_info <- paste0('<span aria-label="', prison_sentencing_system_tooltip, '" tabindex="0" role="button">', prison_sentencing_system_info, '</span>')








# parole_eligibility_criteria <- HTML('
# <ul style="margin-top: 10px; margin-bottom: 10px; list-style-position: outside; padding-left: 20px;">
#     <li style="margin-bottom: 5px;">Parole consideration is typically automatic for most people in prison.</li>
#     <li style="margin-bottom: 5px;">In general, parole consideration occurs after serving 1/3 of the total sentence.</li>
#     <li style="margin-bottom: 5px;">For misdemeanor sentences, a minimum of 6 months must be served.</li>
#     <li style="margin-bottom: 5px;">For felony sentences, a minimum of 9 months must be served.</li>
#     <li style="margin-bottom: 5px;">People in prison serving a sentence of 21 years or more (excluding life sentences) become eligible after serving a 7-year term.</li>
#     <li style="margin-bottom: 5px;">People in prison convicted of certain serious crimes such as aggravated assault, incest, or drug trafficking are not eligible for parole until they have served either 7 years or 1/3 of the prison term, whichever comes first.</li>
# </ul>')
parole_eligibility_criteria <- c("Parole consideration is typically automatic for most people in prison.")
```


```{r}
# data prep by tab

###################

# Highlights

###################

state_data <- parole_eligibility_table_2020 %>% filter(state == state_for_report)
num_people_current   <- sum(state_data$current_count, na.rm = TRUE)
num_people_1_5_years <- sum(state_data$future_1_5_years_count, na.rm = TRUE)


###################

# Overview

###################

# line chart showing the change in prison pop 
# and the change in releases to parole over time
state_line_pop_released_to_parole <- 
  all_line_pop_released_to_parole[[state_for_report]] %>% 
  hc_size(width = 500, height = 400) %>%
  hc_title(text = "Trends in Prison Population, Releases to Parole, and Parole Eligibility")



###################

# Parole Eligibility

###################

# pie chart
state_pie_released_at_ped_2020 <- 
  all_pie_released_at_ped_2020$Georgia %>% 
  hc_size(height = 180, width = 475) %>% 
  hc_colors(colors = c(orange, yellow, teal)) %>% 
  hc_title(text = "Timing of Parole Eligibility and Release in 2020")

# bar chart for most serious sentenced offense
state_bar_parole_elgibility_offense <- 
  all_bar_parole_elgibility_offense$Georgia %>% 
  hc_size(height = 250, width = 475) %>% 
  hc_title(text = "Most Serious Sentenced Offense for People Eligible for Parole but not yet Released in 2020")

# # bar chart - using pie instead
# state_bar_released_at_ped_2020 <- 
#   all_bar_released_at_ped_2020$Georgia %>% 
#   hc_colors(colors = c(orange, teal, yellow)) %>% 
#   hc_size(height = 150, width = 400)

# # save offense pie by state
# state_pie_parole_elgibility_offense <- 
#   all_pie_parole_elgibility_offense$Georgia %>% 
#   hc_size(height = 300, width = 475) %>% 
#   hc_title(text = "Most Serious Sentenced Offense for People Eligible for Parole but not yet Released in 2020")

###################

# Releases from Prison

###################




###################

# Disparities

###################

```

::: less-narrow-section
```{r}
# combine info in one row and center
# highlighted trends numbers
htmltools::div(
  style = "display:flex; flex-direction: row; align-items: center; justify-content: center;",
  div(id = "highlight-text", 
      style = "padding-left: .9em; padding-right: 1em;",
      formattable::comma(num_people_current, digits = 0)
  ),
  div(id = "highlight-text",
      style = "padding-left: 2.2em; padding-right: 2.4em;",
      formattable::comma(num_people_1_5_years, digits = 0)
  ),
  div(style = "display: block; 
              padding-left: 1em; 
              padding-right: 1em; 
              color: #ff6400; 
              font-size: 1.25em; 
              font-family: Graphik; 
              font-weight: bold; 
              text-align: center;",
      prison_sentencing_system)
)

# combine info in one row and center
# highlighted titles for trends numbers
htmltools::div(
  style = "display:flex; flex-direction: row; align-items: center; justify-content: center; ",
  div(id = "bold-text", style = "padding-left: 5em; padding-right: 5em;",
      HTML("Currently Eligible for<br>Parole but in Prison")
      ),
  div(id = "bold-text", style = "padding-left: 5em; padding-right: 5em;",
      HTML("Eligible for Parole in<br>the next 1-5 years")
      ),
  div(id = "bold-text", style = "padding-left: 5em; padding-right: 5em;",
      tippy(prison_sentencing_system_info,
            placement = "bottom",
            flip = TRUE,
            theme = "light",
            tooltip = prison_sentencing_system_tooltip)
      )
)
```
::: 

<br>

```{r}
tags$style(type = "text/css", ".nav-tabs {justify-content: center;}")
tabsetPanel(
  id = "tabsetpanel",
  
  
  #####################################
  
  tabPanel("Overview",
           
  #####################################
  
    br(),
    div(id = "line-graph", state_line_pop_released_to_parole),
    br()
  
  ),
  
  #####################################

  tabPanel("Parole Eligibility",
         
  #####################################
         
  br(), 
  
     ############
     # Set up for columns/Column 1
     ############
     div(id = "column1",
         div(style = "flex: 0 0 50%;",
             div(id = "section-title", "How is Parole Release Eligibility Determined?"), br(),
             div(id = "regular-text", parole_eligibility_criteria),
             div(id = "reactable-table", pe_criteria_table1),
             div(id = "reactable-table", pe_criteria_table2),
         ),
         
         ############
         # Column 2
         ############
         div(id = "column2",
             div(id = "pie-graph", state_pie_released_at_ped_2020)
         )
     ),
  
  br(),
  div(id = "big-section-title", "People who are Eligible for Parole"), 
  br(),
  
     ############
     # Set up for columns/Column 1
     ############
     div(id = "column1",
         div(style = "flex: 0 0 50%;",
             div(id = "section-title", "Info TBD"), br(),
         ),
         
         ############
         # Column 2
         ############
         div(id = "column2",
             div(id = "bar-graph", state_bar_parole_elgibility_offense)
         )
     ),
  
  br(),
  
  ),
  
  #####################################
  
  tabPanel("Releases from Prison",
           
  #####################################
  
  
  ),
  
  #####################################
  
  tabPanel("Disparities",
           
  #####################################
  
  
  ),
  
)
```








